### ISSUE TITLE
Illegal reflective access when calling idle()

### ISSUE THREAD

**Issue by mnlipp** [eclipse-ee4j/angus-mail#26] opened 2022-09-07 16:24 UTC
**Describe the bug**
Illegal reflective access is reported

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.mail.iap.Protocol (file:/home/mnl/.gradle/caches/modules-2/files-2.1/org.eclipse.angus/imap/1.0.0/d4dabb479b54beb8d59d3aecd59bff451ed0ebb3/imap-1.0.0.jar) to field sun.security.ssl.BaseSSLSocketImpl.self
WARNING: Please consider reporting this to the maintainers of com.sun.mail.iap.Protocol
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**To Reproduce**
1. Run the monitor.java example
2. Problem is reported when calling idle()

**Expected behavior**
No warning

**Additional context**
angus 1.0.0

**Comment by jmehrens** [comment] 2022-09-08 01:44
If we undo this reflective access then IdleManager.watch will break.

This message you see should only happen if the SSL implementation [refuses to return a SocketChannel](https://github.com/eclipse-ee4j/angus-mail/blob/0469948e1a9d41c79600c0e8c40592daff6ef97c/providers/imap/src/main/java/com/sun/mail/iap/Protocol.java#L536).  Code was added in JavaMail to find the plain socket that the SSLSocket is wrapping and return the SocketChannel from that.   The code was later updated in [403 - Android SocketChannel workaround not working around](https://github.com/eclipse-ee4j/mail/issues/403) to deal with changes ConscryptSocket.java.

However, after looking at the error message it does bring to light that we need to filter out sockets that are self referential.

**Comment by jmehrens** [comment] 2022-09-08 16:15
This is a bit more interesting than I originally thought.  Per [Socket::getChannel](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/Socket.html#getChannel()):

> A socket will have a channel if, and only if, the channel itself was created via the [SocketChannel.open](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/channels/SocketChannel.html#open()) or [ServerSocketChannel.accept](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/channels/ServerSocketChannel.html#accept()) methods

Sockets in Angus Mail are created from [com.sun.mail.util.SocketFetcher](https://github.com/eclipse-ee4j/angus-mail/blob/41b04f694e7cba8f317f56373cdfccd3d3fa9259/core/src/main/java/com/sun/mail/util/SocketFetcher.java#L143) which will look for various types of socket factories and then use that factory to open the socket connection.

[javax.net.ssl.SSLSocketFactory](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLSocketFactory.html) and [javax.net.SocketFactory](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/SocketFactory.html) only produce Sockets and not SocketChannels.  Therefore, Angus Mail can not satisfy the conditions in the Socket::getChannel API docs without abandoning the legacy mail properties that allow custom socket factories or even the factory that ships with Angus Mail.  I'll have to verify this but it is possible that older JDK socket implementations actually returned a SocketChannel from the socket API if they were connected via a factory and now newer JDK versions enforce the API contract.

**Comment by jmehrens** [comment] 2022-09-09 02:41
After doing some more digging here are the list of changes I need to do for this issue:

1. Only invoke Protocol.findSocketChannel if getChannel is null and  `mail.imap.usesocketchannels=true`.
2. Filter out found sockets that are the same reference as the given socket.
3. Add new tests.
4. Consider adding a property to control reflective access search but I don't think it is needed as there is already a property to use channels.

**Comment by PeteSL** [comment] 2022-09-27 03:09
Throwing my 2 cents in. I have an application that has been using java.mail...>jakarta.mail 1.x->jakarta.mail 2.x for many years. One of the key properties is the ability to -not- use IdleManager but use the .idle() method as the title states of the IMAP provider. I have confirmed this is non-functional (I hide the exceptions so I don't have a handy stack trace) in angus-mail.  Sticking with 2.0.1 until this and the resource issues are officially resolved. I can test the .idle() functionality if you would like.

**Comment by jmehrens** [comment] 2022-09-28 14:03
@PeteSL What version of the JDK are you using to determine that idle is not functional?  I've updated the com.sun.mail.imap.IMAPIdleUntaggedResponseTest locally to include an SSL test so we have coverage of this issue but the test passes even though it is printing the warning output.

[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by com.sun.mail.iap.Protocol (file:/home/jmehrens/eclipse-workspace/angus-mail/providers/angus-mail/target/classes/) to field sun.security.ssl.BaseSSLSocketImpl.self
[ERROR] WARNING: Please consider reporting this to the maintainers of com.sun.mail.iap.Protocol
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.958 s - in com.sun.mail.imap.IMAPIdleUntaggedResponseTest

So my initial guess is wrong about how this would be failing on your system.  The reason that guess is wrong is because of the Socket API contract for getChannel ensures that the channel is null even though the com.sun.mail.iap.Protocol code located the transport socket.

**Comment by PeteSL** [comment] 2022-09-28 14:19
I am currently running JDK 19 and successfully using jakarta.mail and dsn 2.0.1 (yes, I need dsn support as the app does produce specialized NDRs, etc.).  The idle() code is shown below which tells me I should be seeing these types of exceptions but I am not.  The reason I don't report folder/store closed exceptions is because that is a common exception that just requires reconnecting to resolve.  Also, I am not using SSL as the mail server is on a LAN to the application so maybe I need to open a new issue?
`        // Idle thread processing
        for (;;)
        {
            try (IMAPStore mailsrvr = (IMAPStore) parent.sn.getStore())
            {
                mailsrvr.connect(user, password);
                for (;;)
                    try (IMAPFolder inbox = (IMAPFolder) mailsrvr.getFolder("INBOX"))
                    {
                        inbox.open(IMAPFolder.READ_WRITE);
                        for (;;)
                        {
                            while (inbox.getMessageCount() > 0)
                                processInbox(inbox); // Do this before going to idle in case there is mail waiting
                            inbox.idle(true);
                        }
                    }
                    catch (FolderClosedException e)
                    {
                    }
            }
            catch (StoreClosedException e)
            {
            }
            catch (IOException | MessagingException e)
            {
                classlogger.log(Level.WARNING, "IMAP Error", e);
            }
            try
            {
                TimeUnit.SECONDS.sleep(30L);
            }
            catch (InterruptedException e)
            {
                break;
            }
        }
`

**Comment by jmehrens** [comment] 2022-09-28 14:50
@PeteSL The com.sun.mail.iap.Protocol reflective access warning only occurs if the [socket is an instance of an SSLSocket](https://github.com/eclipse-ee4j/angus-mail/blob/41b04f694e7cba8f317f56373cdfccd3d3fa9259/providers/imap/src/main/java/com/sun/mail/iap/Protocol.java#L540).  I'm thinking you might be running into a different issue.  Feel free to create a new issue ticket to track what you are seeing.

**Comment by PeteSL** [comment] 2022-09-28 15:23
Will do.  I'll set up a test bed with a debugger to get a better handle on what is going on and open a new ticket. Since I am not seeing an exception from that code, I am guessing that I am either getting a FolderClosedException or a StoreClosedException (although there may be a deeper root cause shown in the stack).

**Comment by jmehrens** [comment] 2022-12-12 03:08
Committed to angus-mail 1.0.1 RELEASE as:

https://github.com/eclipse-ee4j/angus-mail/commit/46518aad79259d12a115937894ff8f32b86a1a17

**Closed by jmehrens** 2022-12-12 03:08 UTC
