### ISSUE TITLE
I can't send or receive mail

### ISSUE THREAD

**Issue by leonardwoo** [eclipse-ee4j/angus-mail#18] opened 2022-03-30 14:25 UTC
**Describe the bug**
Running the test with the IDE will report the following error
Mar 30, 2022 10:16:04 PM jakarta.mail.Session loadResource
WARNING: expected resource not found: /META-INF/javamail.default.address.map

**To Reproduce**
git clone https://gitlab.com/seppiko/commons-mail/-/tree/dev
> pls change mail account for youself
run SCMTest.java

**Desktop (please complete the following information):**
 - OS: macOS
 - IDE: IntelliJ IDEA 2021.3.3 (Ultimate Edition)

**Mail server:**
 - Protocol being used:  smtp, imap
 - Vendor/product: public mail server

**Additional context**

**Comment by jbescos** [comment] 2022-03-31 10:43
Add this in your module-info.java and try again.

`requires com.sun.mail;`

If compiler complains that it does not find that module, then update the version of the maven-plugin-compiler.

**Comment by leonardwoo** [comment] 2022-03-31 11:46
Thanks, it works. But there is still warning output.

**Comment by jbescos** [comment] 2022-03-31 14:26
What is the warning?. Could you copy-paste it here, please?

**Comment by jbescos** [comment] 2022-03-31 14:35
That file exists in angus-mail.jar. For some reason the mail-api has problems to load that file from the classpath.

I'm going to investigate it. Are you able to see the java process of the test execution?. You can add a Thread.sleep(99999) and meanwhile the execution is hanged, you can check the java process, for example with: $ ps -ef | grep java

Otherwise it is fine, I will find it out.

**Comment by jbescos** [comment] 2022-03-31 15:11
The issue is that jakarta-mail module is trying to get one file that exists in com.sun.mail module. But jakarta-mail module does not require com.sun.mail module.

I possibly need to move that logic out of the jakarta-mail.

The only way you can bypass that warning right now, is removing the module-info.java from your project.

**Comment by jbescos** [comment] 2022-04-01 09:46
We can close this. This is tracked in the other issue you already created:
https://github.com/eclipse-ee4j/mail/issues/598

**Closed by jbescos** 2022-04-01 09:46 UTC
